### ISSUE TITLE
请问有计划添加讯飞等其他平台吗

### ISSUE THREAD

**Issue by despacito008** [funnyzak/tts-now#1]
请问有计划添加讯飞等其他平台吗

**Comment by funnyzak** [comment]
有考虑后续支持。

不过目前对比阿里云语音的合成效果是相关其他平台较好的。

**Comment by despacito008** [comment]
总体上的确是阿里云语音合成效果较好，提议其他平台的原因是这些平台会对某些领域做特殊优化，例如电影解说配音方面

**Comment by funnyzak** [comment]
好的，多谢反馈。后续有时间考虑增加支持。

**Comment by funnyzak** [comment]
已经初步集成讯飞，待进一步优化。欢迎使用
