### ISSUE TITLE
多样化调整语音合成操作的需求

### ISSUE THREAD

**Issue by despacito008** [funnyzak/tts-now#13]
![Screenshot](https://user-images.githubusercontent.com/38098459/180305253-34d5bd85-33e1-4171-a9f5-e07152dfe3ef.png)

微软：https://speech.microsoft.com/audiocontentcreation

**Comment by despacito008** [comment]
https://speech.microsoft.com/audiocontentcreation

**Comment by funnyzak** [comment]
好提议。不过最近还没有这样的计划。 @despacito008
