### ISSUE TITLE
MAC版本提示免费试用期已满

### ISSUE THREAD

**Issue by kaandon** [funnyzak/tts-now#14]
已经购买了阿里云的语音合成TTS资源包，提示如下内容
MAC版  
400 - {"error message". "Gateway:FREE TRIAL EXPIRED:The free trial has
expired!" "error_ code":40000010," request id". "99ebcdbc788e4199abffca021a27af82", "url":"/rest/v1/tts/async","status":400}

**Comment by funnyzak** [comment]
@kaandon 我这边看没问题。

你看你是不是用错服务了，应该是需要使用阿里云长语音服务。
