### ISSUE TITLE
android版TTS

### ISSUE THREAD

**Issue by wangyi1573** [funnyzak/tts-now#15]
**Is your feature request related to a problem? Please describe.**
其实这个项目 可以做成一个安卓TTS的APP阿里有语音合成工具比很多手机自带的TTS效果好，做一个APP应该会有市场前景
**Describe the solution you'd like**

**Additional context**

**Comment by funnyzak** [comment]
好像很多厂商自家就带TTS移动端工具。

做类似工具感觉意义不大，小众，还要再开坑。

@wangyi1573

**Comment by ghost** [comment]
手机厂商也不重视，几乎就没有真正好用的系统TTS。市面上也没啥人爱做，我没有看到过这方面的商业软件。还是有需求的，比如一些epub阅读器可以tts😊，有市场🤣
