### ISSUE TITLE
批量导入文本，识别出来乱码

### ISSUE THREAD

**Issue by wangcanyu** [funnyzak/tts-now#5]
如
![微信图片_20220124114726](https://user-images.githubusercontent.com/98297885/150718991-d70127ed-59f5-4822-9011-54e916b33ab7.png)
题

**Comment by funnyzak** [comment]
试着文本文件用 utf-8 编码

**Comment by wangcanyu** [comment]
> 试着文本文件用 utf-8 编码

解决了，果然是这回事，多谢作者。软件特别好，基本可以说tts软件里最好看的。建议导出的音频和文本文件同名，不然分不清楚。

**Comment by funnyzak** [comment]
👌。会考虑调整优化
