### ISSUE TITLE
在阿里云里面添加了自己录制的声音模型，有办法在软件里调用不？

### ISSUE THREAD

**Issue by wangcanyu** [funnyzak/tts-now#6]
![image](https://user-images.githubusercontent.com/98297885/153614315-df95c1ef-58a7-4105-88e9-7320a595bb4b.png)
阿里云里面添加了自己录制的声音模型，有办法在软件里调用不？

**Comment by funnyzak** [comment]
暂时还没做这块

**Comment by linsamasama** [comment]
能集成一下微软的么

**Comment by linsamasama** [comment]
> 暂时还没做这块
能集成一下微软的么

**Comment by funnyzak** [comment]
> > 暂时还没做这块
> > 能集成一下微软的么

还没看这块，后面找时间会集成其他平台的。
