### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by EthanYimmmm** [funnyzak/tts-now#71]
### Description

能不能输出的文件格式可以标记出是哪个说话人捏？这样针对某些做kws的朋友会友好一些。如果再增加所有说话人的同一个本文的audio批量导出就更好用啦。另外感谢您的分享，尤其是批量导出功能很好用。

### Why

这样针对某些做kws的朋友会友好一些

### Alternatives

现在KWS的一些产品趋势是用合成的音频进行训练，能减少购买真实语料的成本，所以这个工具对我们来说还是比较方便的，但是还能再增加Description里提到的两个功能就更好啦^_^

**Comment by funnyzak** [comment]
@EthanYimmmm 感谢你的建议。后续有时间会考虑加入。
