### ISSUE TITLE
大佬如果exe安装我想用阿里云自己的声音（新出的）

### ISSUE THREAD

**Issue by liuruidong4** [funnyzak/tts-now#9]
voice需要替换成自己的 可以怎么设置一下吗？不懂
本来想找下内置的把一个改了 能力有限完全找不到在哪

**Comment by funnyzak** [comment]
目前都是用的云现成的语音库代码，自定义的目前还没去看API。

**Comment by waitmap** [comment]
能否调用自定义的声音呢？阿里云是有接口的


通过代码调用控制台中定制的音色
定制完成后，推荐您使用语音合成接口调用该声音。更多内容，请参见[语音合成-接口说明](https://help.aliyun.com/document_detail/84435.htm)。

调用定制声音需要在语音合成页面，将个性化人声的模型调用ID填入voice中，同时还需要您增加定制参数enable_ptts，示例代码如下。

synthesizer.setVoice("${模型调用ID}");
synthesizer.addCustomedParam("enable_ptts", true);
